version: '3.8'
services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=getstickbugged

  speedtest:
    image: speedtest2influx:latest
    container_name: speedtest
    environment:
      - INFLUXDV_ADDRESS=influxdb
      - INFLUXDB_PORT=8086
      - INFLUXDB_DATABASE=speedtests
      - INFLUXDB_USERNAME=admin
      - INFLUXDB_PASSWORD=getstickbugged
      - SPEEDTEST_INTERVAL=300s
#      - SPEEDTEST_SERVER_ID=
#      - SPEEDTEST_SERVER_NAME=
      - LOGGING_LEVEL=info
    depends_on: 
      - influxdb
    restart: always
